CREATE OR REPLACE FUNCTION public."CEL_TRIGGER01" (
)
RETURNS trigger AS
$body$
DECLARE
BEGIN
  IF NEW.EVENTTYPE='LINKEDID_END' THEN
	INSERT INTO CEL_JOBS(LINKEDID, EVENT, DESCR) VALUES(NEW.LINKEDID, 'CHAN_CLOSED', 'TEST');
    perform cel_parse_by_linkedid(NEW.LINKEDID, 'cel_tr01');
  END IF;
  RETURN NEW;    
END;
$body$
LANGUAGE 'plpgsql'
VOLATILE
CALLED ON NULL INPUT
SECURITY INVOKER
COST 100;
